replicaCount: 1

image:
  repository: joshirishabh631/demo-app
  tag: 1fac3401d903c01fd94c6c04fbd7ef68bbf7df45
  pullPolicy: Always

service:
  type: NodePort
  port: 5000

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi
