replicaCount: 1

image:
  repository: joshirishabh631/demo-app
  tag: fd79c6dd634cd7ea20f1690c63f32347dd6a5769
  pullPolicy: Always

service:
  type: NodePort
  port: 5000

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi
